//
//  LocationDetailRouter.swift
//  SegurosMtyiOS
//
//  Created by Isidro Adan Garcia Solorio  on 1/2/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LocationDetailRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LocationDetailDataPassing {
    var dataStore: LocationDetailDataStore? { get }
}

class LocationDetailRouter: NSObject, LocationDetailRoutingLogic, LocationDetailDataPassing {
    weak var viewController: LocationDetailViewController?
    var dataStore: LocationDetailDataStore?
}
