//
//  EditPasswordModels.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 28/12/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum EditPasswordStatus {
    case ok
    case invalidPassword(reattempsLeft:Int, message:String)
    case unauthorized(message: String)
    case noInternet(message: String)
    case other(message:String)
    
}

enum EditPassword {
    // MARK: Use cases
    
    enum Something {
        struct Request { }
        struct Response {
            var error:Swift.Error?
        }
        
        struct ViewModel {
            var validatingNewPasswordMessage: String
        }
    }
}
