//
//  AboutInteractor.swift
//  SegurosMtyiOS
//
//  Created by Israel Gutiérrez Castillo on 23/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol AboutBusinessLogic {
    
    func sendMail(_ request: About.SendMail.Request)
    
}

class AboutInteractor: AboutBusinessLogic{
    var presenter: AboutPresentationLogic = AboutPresenter()
    
    func sendMail(_ request: About.SendMail.Request) {
        self.presenter.presentMailComposeVC(request: request)
    }
    
    
}
