//
//  AboutPresenter.swift
//  SegurosMtyiOS
//
//  Created by Israel Gutiérrez Castillo on 23/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import MessageUI

protocol AboutPresentationLogic {
    func presentMailComposeVC(request: About.SendMail.Request)
}

class AboutPresenter: AboutPresentationLogic {
    weak var viewController: AboutViewController?
    
    // MARK: Do something
    
    func presentMailComposeVC(request: About.SendMail.Request) {
        
        let mailComposeVC = MFMailComposeViewController()
        mailComposeVC.setToRecipients([LocalizableKeys.Profile.About.supportEmail])
        let modelView = About.SendMail.ViewModel.init(mailComposeViewController: mailComposeVC)
        
        viewController?.displayMailCompose(viewModel: modelView)
        
        
    }
    
}
