//
//  EmergencyViewController.swift
//  SegurosMtyiOS
//
//  Created by Isidro Adan Garcia Solorio  on 12/27/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EmergencyDisplayLogic: class {
    func displayEmergencyPetition(viewModel: Emergency.Emergency.ViewModel)
}

class EmergencyViewController: UIViewController, EmergencyDisplayLogic {
    var interactor: EmergencyBusinessLogic?
    var router: (NSObjectProtocol & EmergencyRoutingLogic & EmergencyDataPassing)?
    
    @IBOutlet weak var emergency: UILabel!
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = EmergencyInteractor()
        let presenter = EmergencyPresenter()
        let router = EmergencyRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.setupView()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        UIApplication.shared.statusBarStyle = .default
    }
    
    @IBAction func mexicoAssistance(_ sender: UIButton) {
//        IALoader.shared.show(LocalizableKeys.Loader.requestTechnicalAssistance)
        interactor?.emergencyPetition(request: Emergency.Emergency.Request(type: .mexico))
    }
    
    @IBAction func internationlAssistance(_ sender: UIButton) {
        interactor?.emergencyPetition(request: Emergency.Emergency.Request(type: .international))
    }
    
    func displayEmergencyPetition(viewModel: Emergency.Emergency.ViewModel) {
     //   IALoader.shared.hide()
//        if viewModel.isSuccess {
//            let alert = IABlurAlertController(title: nil, message: LocalizableKeys.Emergency.alertok, preferredStyle: .alert)
//            alert.addAction(UIAlertAction(title: LocalizableKeys.General.AlertOptions.accept, style: .default, handler: nil))
//            self.present(alert, animated: true, completion: nil)
//        } else {
//             self.showAlert(with: nil, message: LocalizableKeys.General.serviceError, actionTitle: LocalizableKeys.General.AlertOptions.accept, action: nil)
//        }
    }
    
    func setupView () {
        self.setTranslucentNavigationBar()
        self.navigationController?.navigationBar.titleTextAttributes = [NSAttributedStringKey.foregroundColor: UIColor.smBlue,
                                                                        NSAttributedStringKey.font: UIFont.systemFont(ofSize: 17)]
        self.setCustomBackButton()
        self.title = "Emergencia"
        self.emergency.text = "El botón de emergencia te ayuda a pedir\n asistencia durante cualquier incidente."
    }
    
}
