//
//  EmergencyModels.swift
//  SegurosMtyiOS
//
//  Created by Isidro Adan Garcia Solorio  on 12/27/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum TypePetition: Int {
    case mexico
    case international
}

enum Emergency {
    enum Emergency {
        struct Request {
            var type: TypePetition
        }
        struct Response {
            var isSuccess: Bool
        }
        struct ViewModel {
            var isSuccess: Bool
        }
    }
}
