//
//  EditEmergencyContactModels.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 08/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum EditEmergencyContact {
    // MARK: Use cases
    
    enum SetupEmergencycontact {
        struct Response {
            var emergencyContact: EmergencyContact
        }
        
        struct ViewModel {
            var emergencyContact: EmergencyContact
        }
    }
    
    enum ValidateName {
        struct Request {
            var name: String
        }
        
        struct Response {
            var validationState:TextFieldValidationState
        }
        
        struct ViewModel {
            var validationState:TextFieldValidationState
        }
    }
    
    enum ValidatePhoneNumber {
        struct Request {
            var phoneNumber: String
        }
        
        struct Response {
            var validationState:TextFieldValidationState
        }
        
        struct ViewModel {
            var validationState:TextFieldValidationState
        }
    }
    
    enum ValidateEmail {
        struct Request {
            var email: String
        }
        
        struct Response {
            var validationState:TextFieldValidationState
        }
        
        struct ViewModel {
            var validationState:TextFieldValidationState
        }
    }
    
    enum EditEmergencyContact {
        struct Request {
            var emergencyContactID: Int
            var picture: String?
            var name: String?
            var phone: String?
            var email: String?
        }
        
        struct Response {
            var isSuccess: Bool
        }
        
        struct ViewModel {
            var isSuccess: Bool
        }
    }
    
    enum DeleteEmergencyContact {
        struct Request {
            var emergencyContactID: Int
        }
        
        struct Response {
            var isSuccess: Bool
        }
        
        struct ViewModel {
            var isSuccess: Bool
        }
    }
    
    enum SavePictureEmergencyContact {
        struct Request {
            var picture: IAUIImageView
        }
        
        struct Response {
            var isSuccess: Bool
            var path: String?
        }
        
        struct ViewModel {
            var isSuccess: Bool
            var path: String
        }
    }
}
