//
//  DirectoryMapRouter.swift
//  SegurosMtyiOS
//
//  Created by Isidro Adan Garcia Solorio  on 12/14/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DirectoryChildRoutingLogic {
    func routeToLocationDetail(_ location:Location)
    func routeToFilter()
}

protocol DirectoryChildDataPassing {
    var dataStore: DirectoryDataStore? { get }
}

class DirectoryChildRouter: NSObject, DirectoryChildRoutingLogic, DirectoryChildDataPassing {
    weak var viewController: UIViewController?
    var dataStore: DirectoryDataStore?
    
    // MARK: - Routing
    
    func routeToLocationDetail(_ location:Location) {
        let storyboard = UIStoryboard.directory()
        if let destinationVC = storyboard.instantiateViewController(withIdentifier: "LocationDetail") as? LocationDetailViewController {
          var destinationDS = destinationVC.router?.dataStore
            passDataToLocationDetail(selectedLocation: location, destination: &destinationDS)
            navigateToLocationDetail(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToFilter() {
        let storyboard = UIStoryboard.directoryFilter()
        let destinationVC = storyboard.instantiateInitialViewController() as! MainPulleyViewController
        let parent = viewController?.parent as? DirectoryViewController
        parent?.router?.routeToFilters(destinationVC: destinationVC)
        navigateToFilter(source: viewController! , destination: destinationVC)
    }

    
    // MARK: - Navigation
    func navigateToLocationDetail(source: UIViewController, destination: UIViewController) {
        source.present(destination, animated: true, completion: nil)
    }
    
    func navigateToFilter(source: UIViewController, destination: UIViewController) {
        source.present(destination, animated: true, completion: nil)
    }
    
    func navigateToFilterT(source: UITableViewController, destination: UIViewController) {
        source.present(destination, animated: true, completion: nil)
    }
    
    // MARK: - Passing data
    func passDataToLocationDetail(selectedLocation: Location?, destination: inout LocationDetailDataStore?) {
        destination?.location = selectedLocation
    }
}
