//
//  PolicyCertificateModels.swift
//  SegurosMtyiOS
//
//  Created by Isidro Adan Garcia Solorio  on 2/28/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation

enum PolicyCertificate {
    // MARK: Use cases
    
    enum CertificateFile {
        struct Response {
            var filePath: URL
        }
        struct ViewModel {
            var fileUrl: URL
            var filePath: URL
        }
    }
}
