//
//  PolicyCertificatePresenter.swift
//  SegurosMtyiOS
//
//  Created by Isidro Adan Garcia Solorio  on 2/28/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation

protocol PolicyCertificatePresentationLogic {
    func presentFile(response: PolicyCertificate.CertificateFile.Response)
}

class PolicyCertificatePresenter: PolicyCertificatePresentationLogic {
    weak var viewController: (PolicyCertificateDisplayLogic & ErrorDisplayLogic & ExpiredSessionDisplayLogic)?
    
    func presentFile(response: PolicyCertificate.CertificateFile.Response) {
        // Set view model to use in ViewController if needed
        let url = response.filePath
        let path = url.deletingLastPathComponent()
        let viewModel = PolicyCertificate.CertificateFile.ViewModel(fileUrl: url, filePath: path)
        viewController?.displayFile(viewModel: viewModel)
    }
}

/**
 Extensión para mostrar alerta con un tipo de error
 */
extension PolicyCertificatePresenter: ErrorPresentationLogic {
    func presentError(_ error:Error) {
        switch error {
        case NetworkingError.noInternet:
            viewController?.displayOnscreenError(type: .noInternet)
        default:
            viewController?.displayOnscreenError(type: .noSearchResults)
        }
    }
}

/**
 Extensión para mostrar alerta de expiración de token
 */
extension PolicyCertificatePresenter : ExpiredSessionPresentationLogic {
    func presentExpiredSession() {
        self.viewController?.displayExpiredSession()
    }
}
