//
//  InternationalRouter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 27/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol InternationalRoutingLogic {
    func goToEmergencyViewController()
}

protocol InternationalDataPassing {
    var dataStore: InternationalDataStore? { get }
}

class InternationalRouter: NSObject, InternationalRoutingLogic, InternationalDataPassing {
    weak var viewController: InternationalViewController?
    var dataStore: InternationalDataStore?
    
    // MARK: Routing
    func goToEmergencyViewController() {
        self.viewController?.dismiss(animated: true, completion: nil)
    }
}
