//
//  SplashPresenter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 30/11/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol SplashPresentationLogic {
    func presentAnimationLogo(response: Splash.AnimationLogo.Response.PresenterAnimation)
    func presentVideo(response: Splash.PlayVideo.Response.PresenterPlayVideo)
}

class SplashPresenter: SplashPresentationLogic {
    weak var viewController: SplashDisplayLogic?
    
    // MARK: Do something

    func presentAnimationLogo(response: Splash.AnimationLogo.Response.PresenterAnimation) {
          // asigna la animación a reproducir en el viewModel
        let viewModel = Splash.AnimationLogo.ViewModel.ViewModelAnimation(animationLogo: response.animationLogo)
        viewController?.displayAnimationLogo(viewModel: viewModel)
    }
    
    func presentVideo(response: Splash.PlayVideo.Response.PresenterPlayVideo) {
        // asigna el video a reproducir al viewModel
        let viewModel = Splash.PlayVideo.ViewModel.ViewModelPlayVideo(avPlayer: response.avPlayer)
        viewController?.playVideo(viewModel: viewModel)
    }
}
