//
//  SplashRouter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 30/11/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SplashRoutingLogic {
    func goToLoginViewController(segue: UIStoryboardSegue?)
}

protocol SplashDataPassing {
    var dataStore: SplashDataStore? { get }
}

class SplashRouter: NSObject, SplashRoutingLogic, SplashDataPassing {
    weak var viewController: SplashViewController?
    var dataStore: SplashDataStore?
    
    // MARK: Routing
    
    func goToLoginViewController(segue: UIStoryboardSegue?) {
        //Validar si en el dispostivo ya se ha visto el tutorial
        if UserDefaultsManager.shared.isTutorialShown {
            UIStoryboard.loadWelcome()
        } else {
            UIStoryboard.loadTutorial()
        }
    }
}
