//
//  SplashModels.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 30/11/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Lottie
import AVKit

enum Splash {
    // MARK: Use cases
    
    enum AnimationLogo {
        struct Response {
            struct PresenterAnimation {
                var animationLogo: LOTAnimationView
            }
        }
        
        struct ViewModel {
            struct ViewModelAnimation {
                var animationLogo: LOTAnimationView
            }
        }
    }
    
    enum PlayVideo {
        struct Response {
            struct PresenterPlayVideo {
                var avPlayer: AVPlayer
            }
        }
        
        struct ViewModel {
            struct ViewModelPlayVideo {
                var avPlayer: AVPlayer
            }
        }
    }
}
