//
//  SplashInteractor.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 30/11/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Lottie

protocol SplashBusinessLogic {
    func loadSplashAnimation()
    func loadVideo()
}

protocol SplashDataStore {
}

class SplashInteractor: SplashBusinessLogic, SplashDataStore {
    var presenter: SplashPresentationLogic?
    var worker: SplashWorker?
    
    // MARK: Do something
    
    func loadSplashAnimation() {
        worker = SplashWorker()
        worker?.loadAnimationLogo(completionHandler: { (result) in
             let response = Splash.AnimationLogo.Response.PresenterAnimation(animationLogo: result)
             self.presenter?.presentAnimationLogo(response: response)
        })
    }
    
    func loadVideo() {
        worker = SplashWorker()
        worker?.loadLocalVideo(completionHandler: { (result) in
            let response = Splash.PlayVideo.Response.PresenterPlayVideo(avPlayer: result)
            self.presenter?.presentVideo(response: response)
        })
    }
}
