//
//  TutorialModels.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 02/12/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Lottie

enum Tutorial {
    // MARK: Use cases
    
    enum LoadTutorial {
        struct Response {
            var steps: [StepView]
        }
        
        struct ViewModel {
            var steps: [StepView]
        }
    }
    
    enum SwipeTutorial {
        struct Request {
            var currentStep: Int
        }
        
        struct Response {
            var currentStep: Int
        }
        
        struct ViewModel {
            var firstTick: UIImage
            var secondTick: UIImage
            var thirdTick: UIImage
            var titleCloseButton: String
        }
    }
}
