//
//  TutorialRouter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 02/12/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TutorialRoutingLogic {
    func goToWelcomeViewController(segue: UIStoryboardSegue?)
}

protocol TutorialDataPassing {
    var dataStore: TutorialDataStore? { get }
}

class TutorialRouter: NSObject, TutorialRoutingLogic, TutorialDataPassing {
    weak var viewController: TutorialViewController?
    var dataStore: TutorialDataStore?
    
    // MARK: Routing
    
    func goToWelcomeViewController(segue: UIStoryboardSegue?) {
        UIStoryboard.loadWelcome()
    }
}
