//
//  SelectionPulleyModels.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 20/12/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum SelectionPulley {
    // MARK: Use cases
    
    enum States {
        struct Response {
            var states: [State]
        }
        
        struct ViewModel {
            var states: [State]
        }
    }
    
    enum FilterStates {
        struct Response {
            var states: [State]
        }
        
        struct ViewModel {
            var states: [State]
        }
    }
    
    enum DoctorSpecialities {
        struct Response {
            var specialities: [Specialty]
        }
        
        struct ViewModel {
            var specialities: [Specialty]
        }
    }
    
    enum FilterSpecialities {
        struct Response {
            var specialities: [Specialty]
        }
        
        struct ViewModel {
            var specialities: [Specialty]
        }
    }
}
