//
//  ProfileInformationRouter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 05/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileInformationRoutingLogic {
    func goToDetailEmegerncyContact()
    func goToAddSelectionEmergencyContact()
    func goToAddManualEmergencyContact()
}

protocol ProfileInformationDataPassing {
    var dataStore: ProfileInformationDataStore? { get }
}

class ProfileInformationRouter: NSObject, ProfileInformationRoutingLogic, ProfileInformationDataPassing {
    weak var viewController: ProfileInformationViewController?
    var dataStore: ProfileInformationDataStore?
    
    // MARK: Routing
    func goToDetailEmegerncyContact() {
        if let profileVC = self.viewController?.parent as? ProfileViewController {
            var profileDataStore = profileVC.router?.dataStore
            self.passEmergencyContacts(to: &profileDataStore!)
            profileVC.router?.routeToDetailEmergencyContact()
        }
    }
    
    private func passEmergencyContacts(to destination: inout ProfileDataStore) {
        guard let data = self.dataStore else { return }
        destination.emergencyContact = data.emergencyContact
    }
    
    func goToAddSelectionEmergencyContact() {
        let storyBoard = UIStoryboard.emergencyContacts()
        let navigationVC = storyBoard.instantiateViewController(withIdentifier: "NavigationSelectContact") as! UINavigationController
        self.viewController?.present(navigationVC, animated: true, completion: nil)
    }
    
    func goToAddManualEmergencyContact() {
        let storyBoard = UIStoryboard.emergencyContacts()
        let addEmergencyContactVC = storyBoard.instantiateViewController(withIdentifier: "AddEmergencyContactViewController") as! AddEmergencyContactViewController
        self.viewController?.present(addEmergencyContactVC, animated: true, completion: nil)
    }
}
