//
//  ProfileInformationModels.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 05/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum ProfileInformation {
    // MARK: Use cases
    
    enum GetEmergencyContacts {
        struct Response {
            var emergencyContacts: [EmergencyContact]?
            var error: Swift.Error?
        }
        struct ViewModel {
            var emergencyContacts: [EmergencyContact]?
            var errorMessage: String?
        }
    }
  
    enum SetEmergencyContact {
        struct Request {
            var emergencyContact: EmergencyContact?
        }
    }
    
}
