//
//  CheckCodeRouter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 07/12/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CheckCodeRoutingLogic {
    func goToMenu()
    func goToRenewPasswordViewController()
}

protocol CheckCodeDataPassing {
    var dataStore: CheckCodeDataStore? { get set }
}

class CheckCodeRouter: NSObject, CheckCodeRoutingLogic, CheckCodeDataPassing {
    weak var viewController: CheckCodeViewController?
    var dataStore: CheckCodeDataStore?
    
    // MARK: Routing
    
    func goToMenu() {
        UIStoryboard.loadMenu()
    }
    
    func goToRenewPasswordViewController() {
        let storyBoard = UIStoryboard.recoverPassword()
        guard let renewPasswordVC = storyBoard.instantiateViewController(withIdentifier: "RenewPasswordViewController") as? RenewPasswordViewController else { return }
        renewPasswordVC.router?.dataStore?.phoneNumber = dataStore?.phoneNumber ?? ""
        renewPasswordVC.router?.dataStore?.smsCode = dataStore?.smsCode ?? ""
        renewPasswordVC.router?.dataStore?.serverTimestamp = dataStore?.serverTimestamp
        viewController?.show(renewPasswordVC, sender: nil)
    }
}
