//
//  PolicySelectionBeneficiariesToWalletInteractor.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 01/03/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import UIKit

protocol PolicySelectionBeneficiariesToWalletBusinessLogic {
    func getBeneficiares()
    func setBeneficiareSelected(beneficiare: Beneficiarie?, indexPath: IndexPath)
    func showWallet()
}

protocol PolicySelectionBeneficiariesToWalletDataStore {
    var policy: InsurancePolicy? { get set }
    var beneficiaries: [Beneficiarie]? { get set }
    var beneficiareSelected: Beneficiarie? { get set }
    var indexPathSelected: IndexPath? { get set }
    var isTitularBeneficiare: Bool { get set }
}

class PolicySelectionBeneficiariesToWalletInteractor: PolicySelectionBeneficiariesToWalletBusinessLogic, PolicySelectionBeneficiariesToWalletDataStore {
    var presenter: PolicySelectionBeneficiariesToWalletPresentationLogic?
    
    // MARK: DataStore
    var policy: InsurancePolicy?
    var beneficiaries: [Beneficiarie]?
    var beneficiareSelected: Beneficiarie?
    var indexPathSelected: IndexPath?
    var isTitularBeneficiare = true
    
    // MARK: Do something
    func getBeneficiares() {
        if let _ = self.beneficiaries {
            let response = PolicySelectionBeneficiariesToWallet.GetBeneficiares.Response(beneficiares: self.beneficiaries!)
            self.presenter?.presentBeneficiares(response: response)
        } else {
            self.presenter?.presentError()
        }
    }
    
    func setBeneficiareSelected(beneficiare: Beneficiarie?, indexPath: IndexPath) {
        if indexPath.row == 0 {
            self.isTitularBeneficiare = true
        } else {
            self.isTitularBeneficiare = false
        }
        
        self.indexPathSelected = indexPath
        self.beneficiareSelected = beneficiare
    }
    
    func showWallet() {
        if let _ = self.beneficiareSelected {
          self.presenter?.presentShowWallet()
        } else if self.indexPathSelected?.row == 0 {
          self.presenter?.presentShowWallet()
        }
    }
}
