//
//  SplashWorker.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 30/11/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Lottie
import AVKit

class SplashWorker {
    
    func loadAnimationLogo(completionHandler: @escaping (LOTAnimationView) -> Void) {
        let animation = LOTAnimationView.init(name: "splashLogo")
        completionHandler(animation)
    }
    
    func loadLocalVideo(completionHandler: @escaping (AVPlayer) -> Void) {
        let videoURL = Bundle.main.url(forResource: "dummy", withExtension: "mp4")
        let avPlayer = AVPlayer(url: videoURL! as URL)
        completionHandler(avPlayer)
    }
    
}
