//
//  TutorialWorker.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 02/12/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Lottie

class TutorialWorker {
    func loadSteps(completionHandler: @escaping (Tutorial.LoadTutorial.Response) -> Void) {
        var steps = [StepView]()
        let animations = getArrayAnimationsForDevice()
        let titles = ["Bienvenido(a) a \n MiSeguroMty", "Conoce tus beneficios", "Para tu seguridad"]
        let bodies = ["Todo lo que necesitas para administrar \n tu Seguro de Gastos Médicos Mayores \n en la palma de tu mano.", "Acceso al directorio de red \n médica, reporte de emergencias y \n consulta tus pólizas de Gastos \n Médicos Mayores.", "Es importante que no compartas \n tu usuario y contraseña para \n que mantengas siempre tu \n información segura."]
        
        for index in 0...2 {
            let lottieAnimation = LOTAnimationView.init(name: animations[index])
            let step = StepView(frame: CGRect(), animation: lottieAnimation, title: titles[index], body: bodies[index])
            steps.append(step)
        }
        
        let response = Tutorial.LoadTutorial.Response(steps: steps)
        
        completionHandler(response)
    }
    
    private func getArrayAnimationsForDevice() -> [String] {
        if DeviceDetector.DeviceType.IS_IPHONE_5 {
            return ["tutorialStep1iPhone5", "tutorialStep2iPhone5", "tutorialStep3iPhone5"]
        } else  if DeviceDetector.DeviceType.IS_IPHONE_6P_7P_8P {
            return ["tutorialStep1Plus", "tutorialStep2Plus", "tutorialStep3Plus"]
        }else {
            return ["tutorialStep1", "tutorialStep2", "tutorialStep3"]
        }
    }
}
