//
//  DirectoryModels.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 05/12/17.
//  Copyright (c) 2017 Erwin Jonnatan Perez Téllez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum Directory {
    // MARK: Use cases
    
    enum Locations {
        struct Request {
            var searchTerms: String?
        }
    }
    
    enum LocationSearchSuggestions {
        struct Request {
            var searchTerms: String
        }
    }
}
