//
//  PolicyAssistanceDetailModels.swift
//  SegurosMtyiOS
//
//  Created by Isidro Adan Garcia Solorio  on 1/24/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum PolicyAssistanceDetail {
    // MARK: Use cases
    
    enum Something {
        struct Request { }
        struct Response { }
        struct ViewModel {
            var assistanceType: AssistanceType
        }
    }
}
