//
//  PolicyAssistanceDetailPresenter.swift
//  SegurosMtyiOS
//
//  Created by Isidro Adan Garcia Solorio  on 1/24/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol PolicyAssistanceDetailPresentationLogic {
    func presentData(response: AssistanceType)
    func presentRemoteData(response: [AssistanceItem])
}

class PolicyAssistanceDetailPresenter: PolicyAssistanceDetailPresentationLogic {
    weak var viewController: (PolicyAssistanceDetailDisplayLogic & ExpiredSessionDisplayLogic)?
    
    // MARK: Do something
    
    func presentData(response: AssistanceType) {
        let viewModel = PolicyAssistanceDetail.Something.ViewModel(assistanceType: response)
        viewController?.displayData(viewModel: viewModel)
    }
    
    func presentRemoteData(response: [AssistanceItem]) {
        self.viewController?.displayRemoteData(viewModel: response)
    }
}

extension PolicyAssistanceDetailPresenter : ErrorPresentationLogic {
    func presentError(_ error:Error) {
        switch error {
        case NetworkingError.noInternet:
            self.viewController?.displayError(type: .noInternet, message: LocalizableKeys.General.noInternet)
        default:
            self.viewController?.displayError(type: .noInternet, message: LocalizableKeys.General.serviceError)
        }
    }
}

extension PolicyAssistanceDetailPresenter : ExpiredSessionPresentationLogic {
    func presentExpiredSession() {
        self.viewController?.displayExpiredSession()
    }
}

