//
//  EmergencyMexicoModels.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 27/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum EmergencyMexico {
    // MARK: Use cases
    
    enum CallAtPhone {
        struct Request {
            var assistancePhone: AssistancePhone
        }
    }
}
