//
//  EmergencyMexicoRouter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 27/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EmergencyMexicoRoutingLogic {
    func goToEmergencyViewController()
}

protocol EmergencyMexicoDataPassing {
    var dataStore: EmergencyMexicoDataStore? { get }
}

class EmergencyMexicoRouter: NSObject, EmergencyMexicoRoutingLogic, EmergencyMexicoDataPassing {
    weak var viewController: EmergencyMexicoViewController?
    var dataStore: EmergencyMexicoDataStore?
    
    // MARK: Routing
    func goToEmergencyViewController() {
        self.viewController?.dismiss(animated: true, completion: nil)
    }
}
