//
//  EmergencyMexicoInteractor.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 27/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol EmergencyMexicoBusinessLogic {
    func doCallAtPhone(request: EmergencyMexico.CallAtPhone.Request)
}

protocol EmergencyMexicoDataStore {
    //var myDataStoreVar: String { get set }
}

class EmergencyMexicoInteractor: EmergencyMexicoBusinessLogic, EmergencyMexicoDataStore {
    var worker: EmergencyWorker?
    
    // MARK: Do something
    
    func doCallAtPhone(request: EmergencyMexico.CallAtPhone.Request) {
        if worker == nil {
            worker = EmergencyWorker()
        }
        
        worker?.callAtPhone(assistancePhone: request.assistancePhone)
    }
}
