//
//  FormSceneRouter.swift
//  SegurosMtyiOS
//
//  Created by Claudia Mariana Parente Ramos on 18/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FormSceneRoutingLogic {
    func goToCheckCode()
}

protocol FormSceneDataPassing {
    var dataStore: FormSceneDataStore? { get set }
}

class FormSceneRouter: NSObject, FormSceneRoutingLogic, FormSceneDataPassing {
    weak var viewController: FormViewController?
    var dataStore: FormSceneDataStore?
    
    // MARK: Routing
    
    func goToCheckCode() {
        let storyBoard = UIStoryboard.recoverPassword()
        let checkCodeVC = storyBoard.instantiateViewController(withIdentifier: "CheckCodeViewController") as! CheckCodeViewController
        checkCodeVC.router?.dataStore?.phoneNumber = dataStore?.phone ?? ""
        checkCodeVC.router?.dataStore?.password = dataStore?.password ?? ""
        checkCodeVC.router?.dataStore?.validationCodeProccessType = .activate
        viewController?.show(checkCodeVC, sender: nil)
    }
}
