//
//  FormSceneModels.swift
//  SegurosMtyiOS
//
//  Created by Claudia Mariana Parente Ramos on 18/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum FormScene {
    // MARK: Use cases
    
    enum Something {
        struct Request { }
        struct Response { }
        struct ViewModel {
        }
    }
}
