//
//  LoginRouter.swift
//  SegurosMtyiOS
//
//  Created by Isidro Adan Garcia Solorio  on 12/1/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginRoutingLogic {
    func goToMenu()
    func goToRecoverPasswordViewController(type: RecoverPasswordType)
    func goToCheckCode(validationCodeProccessType:ValidationCodeProccessType)
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get set }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Routing
    
    func goToMenu() {
        UIStoryboard.loadMenu()
    }
    
    func goToRecoverPasswordViewController(type: RecoverPasswordType) {
        let storyBoard = UIStoryboard.recoverPassword()
        guard let recoverPasswordVC = storyBoard.instantiateInitialViewController() as? RecoverPasswordViewController else { return }
        
        recoverPasswordVC.router?.dataStore?.phoneNumber = dataStore?.phoneNumber ?? ""
        recoverPasswordVC.router?.dataStore?.recoverPasswordType = type
        viewController?.show(recoverPasswordVC, sender: nil)
    }
    
    func goToCheckCode(validationCodeProccessType:ValidationCodeProccessType) {
        let storyBoard = UIStoryboard.recoverPassword()
        let checkCodeVC = storyBoard.instantiateViewController(withIdentifier: "CheckCodeViewController") as! CheckCodeViewController
        checkCodeVC.router?.dataStore?.phoneNumber = dataStore?.phoneNumber ?? ""
        checkCodeVC.router?.dataStore?.password = dataStore?.password ?? ""
        checkCodeVC.router?.dataStore?.validationCodeProccessType = validationCodeProccessType
        viewController?.show(checkCodeVC, sender: nil)
    }
}

