//
//  LoginModels.swift
//  SegurosMtyiOS
//
//  Created by Isidro Adan Garcia Solorio  on 12/1/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum LoginStatus {
    case ok
    case recoverPassword(type:RecoverPasswordType, message:String)
    case activateAccount(message:String)
    case invalidPassword(reattempsLeft:Int, message:String)
    case invalidInput
    case other(message:String)
}

enum Login {
    // MARK: Use cases
    enum ValidatePhoneNumber {
        struct Response {
            var phoneNumber:String
            var userName:String
            var isFirstEntry:Bool
            var error:Swift.Error?
        }
        
        struct ViewModel {
            var phoneNumber:String
            var validationState:TextFieldValidationState
            var isFirstEntry:Bool
            var alertString:String?
        }
    }
    
    enum Login {
        struct Response {
            var error:Swift.Error?
        }
        struct ViewModel {
            var status: LoginStatus
        }
    }
}
