//
//  LocationsTableModels.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 15/12/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreLocation

enum LocationsTable {
    // MARK: Use cases
    
    enum Locations {
        struct Response {
            var locations:[Location]
        }
        struct ViewModel {
            var name: String
            var image: String
            var address: String
            var phone: String
            var isFavorite: Bool
            var distanceString:String?
        }
    }
}
