//
//  RenewPasswordModels.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 09/12/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum RenewPasswordStatus {
    case success(message: String)
    case invalidPhoneOrCode(message: String)
    case errorWithData(message: String)
    case invalidInputs()
    case other(message:String)
}

enum RenewPassword {
    // MARK: Use cases
    
    enum ConfirmPassword {
        struct Response {
            var isSamePassword: Bool
        }
        struct ViewModel {
            var isSamePassword: Bool
        }
    }
    
    enum RenewPAssword {
        struct Response {
            var error:Swift.Error?
        }
        struct ViewModel {
            var status: RenewPasswordStatus
        }
    }
}
