//
//  RenewPasswordRouter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 09/12/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RenewPasswordRoutingLogic {
    func goToMenu()
}

protocol RenewPasswordDataPassing {
    var dataStore: RenewPasswordDataStore? { get set }
}

class RenewPasswordRouter: NSObject, RenewPasswordRoutingLogic, RenewPasswordDataPassing {
    weak var viewController: RenewPasswordViewController?
    var dataStore: RenewPasswordDataStore?
    
    // MARK: Routing
    
    func goToMenu() {
        UIStoryboard.loadMenu()
    }
}
