//
//  FiltersPresenter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 18/12/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol FiltersPresentationLogic {
}

class FiltersPresenter: FiltersPresentationLogic {
    weak var viewController: FiltersDisplayLogic?
}
