//
//  FiltersInteractor.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 18/12/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol FiltersBusinessLogic {
    
}

protocol FiltersDataStore {
    var selectedServices: [ServiceType] { get set }
    var isFavoritesOnly: Bool { get set }
    var isPlanIncludedOnly: Bool { get set }
    var selectedState: State? { get set }
    var doctorTypes: [Specialty] { get set }
}

class FiltersInteractor: FiltersBusinessLogic, FiltersDataStore {
    var presenter: FiltersPresentationLogic?
    var worker: FiltersWorker?
    
    // MARK: DataStore
    
    var selectedServices: [ServiceType] = []
    var isFavoritesOnly: Bool = false
    var isPlanIncludedOnly: Bool = false
    var selectedState: State?
    var doctorTypes: [Specialty] = []
    
}
