//
//  PrivacyInteractor.swift
//  SegurosMtyiOS
//
//  Created by Mariana on 26/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol PrivacyBusinessLogic {
    func getResponseURL(request: Privacy.WebViewPrivacy.Request)
}

protocol PrivacyDataStore {
    //var myDataStoreVar: String { get set }
}

class PrivacyInteractor: PrivacyBusinessLogic, PrivacyDataStore {
    var presenter: PrivacyPresentationLogic?
    
    // MARK: DataStore
    
    //var myDataStoreVar: String = ""
    
    // MARK: Do something
    
    func getResponseURL(request: Privacy.WebViewPrivacy.Request) {
        
        if ReachabilityManager.shared.isOnline {
            presenter?.presentSomething(response: Privacy.WebViewPrivacy.Response(isSuccess: true, url: request.url))
        } else {
            presenter?.presentSomething(response: Privacy.WebViewPrivacy.Response(isSuccess: false, url: ""))
        }
        
    }
}
