//
//  PrivacyPresenter.swift
//  SegurosMtyiOS
//
//  Created by Mariana on 26/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol PrivacyPresentationLogic {
    func presentSomething(response: Privacy.WebViewPrivacy.Response)
}

class PrivacyPresenter: PrivacyPresentationLogic {
    weak var viewController: PrivacyDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Privacy.WebViewPrivacy.Response) {
        
        if response.isSuccess {
            viewController?.displayWebView(viewModel: Privacy.WebViewPrivacy.ViewModel(url: response.url!))
        } else {
            viewController?.displayError()
        }
    }
}
