//
//  SelectContactFromDeviceRouter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 22/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SelectContactFromDeviceRoutingLogic {
    func goToPerfilViewController()
    func goToAddManualEmergencyContact()
    func goToPerfilViewControllerAndRefreshEmergencyContacts()
}

protocol SelectContactFromDeviceDataPassing {
    var dataStore: SelectContactFromDeviceDataStore? { get }
}

class SelectContactFromDeviceRouter: NSObject, SelectContactFromDeviceRoutingLogic, SelectContactFromDeviceDataPassing {
    weak var viewController: SelectContactFromDeviceViewController?
    var dataStore: SelectContactFromDeviceDataStore?
    
    // MARK: Routing
    
    func goToPerfilViewController() {
        self.viewController?.navigationController?.dismiss(animated: true, completion: nil)
    }
    
    func goToAddManualEmergencyContact() {
        if let menuVC = self.viewController?.navigationController?.presentingViewController as? MenuViewController {
            if let navigationProfileVC = menuVC.viewControllers?.first as? UINavigationController {
                if let profileVC = navigationProfileVC.viewControllers.first as? ProfileViewController {
                    if let pruebaVC = profileVC.childViewControllers[0] as? ProfileInformationViewController {
                        self.viewController?.navigationController?.dismiss(animated: true, completion: {
                            pruebaVC.router?.goToAddManualEmergencyContact()
                        })
                    }
                }
            }
        }
    }
    
    func goToPerfilViewControllerAndRefreshEmergencyContacts() {
        if let menuVC = self.viewController?.navigationController?.presentingViewController as? MenuViewController {
            if let navigationProfileVC = menuVC.viewControllers?.first as? UINavigationController {
                if let profileVC = navigationProfileVC.viewControllers.first as? ProfileViewController {
                    if let pruebaVC = profileVC.childViewControllers[0] as? ProfileInformationViewController {
                        self.viewController?.navigationController?.dismiss(animated: true, completion: {
                            pruebaVC.emergencyContacts = nil
                            pruebaVC.reloadEmergencyContacts()
                            self.viewController?.navigationController?.dismiss(animated: true, completion: nil)
                        })
                    }
                }
            }
        }
    }
}
