//
//  SelectContactFromDeviceModels.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 22/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum SelectContactFromDevice {
    // MARK: Use cases
    
    enum GetContacts {
        struct Response {
            var contacts: [Contact]
        }
        struct ViewModel {
            var contacts: [Contact]
        }
    }
    
    enum GroupContactsByAlphabet {
        struct Request {
            var contacts: [Contact]
        }
        
        struct Response {
            var groupContacts: [String: [Contact]]
        }
        struct ViewModel {
            var groupContacts: [String: [Contact]]
        }
    }
    
    enum AddemergencyContact {
        struct Request {
            var contact: Contact
        }
        
        struct Response {
            var noDataContact: NoDataContact
        }
        
        struct ViewModel {
            var errorMessage: String
        }
    }
    
    enum GroupContactsFilteredBySearchText {
        struct Request {
            var searchText: String
        }
        
        struct Response {
            var groupContacts: [String: [Contact]]
        }
        struct ViewModel {
            var groupContacts: [String: [Contact]]
        }
    }
}
