//
//  RecoverPasswordModels.swift
//  SegurosMtyiOS
//
//  Created by Erwin Jonnatan Perez Téllez on 06/12/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum RecoverPasswordType: Int {
    case new = 1
    case reset = 2
}

enum RecoverPassword {
    // MARK: Use cases

    enum ValidatePhoneNumber {
        struct Response {
            var phoneNumber:String
            var userName:String
            var error:Swift.Error?
        }
        
        struct ViewModel {
            var phoneNumber:String
            var validationState:TextFieldValidationState
            var alertString:String?
        }
    }
    
    enum GenerateCodeToRecoverPassword {
        struct Response {
            var error:Swift.Error?
        }
        struct ViewModel {
            var success:Bool
            var message:String?
        }
    }
}
