//
//  DetailEmergencyContactViewController.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 07/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailEmergencyContactDisplayLogic: class {
    func displaySomething(viewModel: DetailEmergencyContact.Something.ViewModel)
}

class DetailEmergencyContactViewController: IAPopupViewController, DetailEmergencyContactDisplayLogic {
    var interactor: DetailEmergencyContactBusinessLogic?
    var router: (NSObjectProtocol & DetailEmergencyContactRoutingLogic & DetailEmergencyContactDataPassing)?
    
    @IBOutlet weak var picture: IAUIImageView!
    @IBOutlet weak var name: UILabel!
    @IBOutlet weak var phone: UILabel!
    @IBOutlet weak var email: UILabel!
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = DetailEmergencyContactInteractor()
        let presenter = DetailEmergencyContactPresenter()
        let router = DetailEmergencyContactRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: Do something
    @IBAction func closePressed(_ sender: Any) {
        super.close(completion: {
            self.dismiss(animated: false, completion: nil)
        })
    }
    
    override func setupUI() {
        super.setupUI()
        self.view.backgroundColor = UIColor.clear
        self.name.text = self.router?.dataStore?.emergencyContact.name ?? LocalizableKeys.General.noInformation
        self.phone.text = self.router?.dataStore?.emergencyContact.phone ?? LocalizableKeys.General.noInformation
        self.email.text = self.router?.dataStore?.emergencyContact.email ?? LocalizableKeys.General.noInformation
        
        self.picture.image = FilesManager.getImageInDirectoryInsideDocuments(directory: UserDefaultsManager.shared.directoryPicturesEmergencyContacts, name: self.router?.dataStore?.emergencyContact.picture ?? "") ?? UIImage(named: "defaultAvatar")
        
    }
    
    @IBAction func editPressed(_ sender: Any) {
        self.router?.goToEditEmergencyContact()
    }
    
    func displaySomething(viewModel: DetailEmergencyContact.Something.ViewModel) {
        //someTextField.text = viewModel.myViewModelVar
    }
}
