//
//  DetailEmergencyContactPresenter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 07/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol DetailEmergencyContactPresentationLogic {
    func presentSomething(response: DetailEmergencyContact.Something.Response)
}

class DetailEmergencyContactPresenter: DetailEmergencyContactPresentationLogic {
    weak var viewController: DetailEmergencyContactDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: DetailEmergencyContact.Something.Response) {
        let viewModel = DetailEmergencyContact.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
