//
//  DetailEmergencyContactModels.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 07/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum DetailEmergencyContact {
    // MARK: Use cases
    
    enum Something {
        struct Request { }
        struct Response { }
        struct ViewModel { }
    }
}
