//
//  WelcomeMenuSceneInteractor.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 04/12/17.
//  Copyright (c) 2017 Erwin Jonnatan Perez Téllez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol WelcomeMenuSceneBusinessLogic {
    func loadUser()
}

protocol WelcomeMenuSceneDataStore {
    //var myDataStoreVar: String { get set }
}

class WelcomeMenuSceneInteractor: WelcomeMenuSceneBusinessLogic, WelcomeMenuSceneDataStore {
    var presenter: WelcomeMenuScenePresentationLogic?
    var worker: WelcomeMenuSceneWorker?
    
    // MARK: Do something
    
    func loadUser() {
        worker = WelcomeMenuSceneWorker()
        if let response = worker?.getUser() {
            self.presenter?.presentUser(response: response)
        }
    }
}
