//
//  WelcomeMenuSceneRouter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 04/12/17.
//  Copyright (c) 2017 Erwin Jonnatan Perez Téllez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WelcomeMenuSceneRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol WelcomeMenuSceneDataPassing {
    var dataStore: WelcomeMenuSceneDataStore? { get }
}

class WelcomeMenuSceneRouter: NSObject, WelcomeMenuSceneRoutingLogic, WelcomeMenuSceneDataPassing {
    weak var viewController: WelcomeMenuSceneViewController?
    var dataStore: WelcomeMenuSceneDataStore?
    
    // MARK: Routing
    
}
