//
//  WelcomeMenuScenePresenter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 04/12/17.
//  Copyright (c) 2017 Erwin Jonnatan Perez Téllez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol WelcomeMenuScenePresentationLogic {
    func presentUser(response: WelcomeMenuScene.LoadUser.Response)
}

class WelcomeMenuScenePresenter: WelcomeMenuScenePresentationLogic {
    weak var viewController: WelcomeMenuSceneDisplayLogic?
    
    // MARK: Do something
    
    func presentUser(response: WelcomeMenuScene.LoadUser.Response) {
        let viewModel = WelcomeMenuScene.LoadUser.ViewModel(name: response.name, date: response.date)
        viewController?.displayInfoUser(viewModel: viewModel)
    }
}
