//
//  WelcomeMenuSceneModels.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 04/12/17.
//  Copyright (c) 2017 Erwin Jonnatan Perez Téllez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum WelcomeMenuScene {
    // MARK: Use cases
    
    enum LoadUser {
        struct Response {
            var name: String
            var date: String
        }
        
        struct ViewModel {
            var name: String
            var date: String
        }
    }
}
