//
//  AddPolicyRouter.swift
//  SegurosMtyiOS
//
//  Created by Israel Gutiérrez Castillo on 17/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddPolicyRoutingLogic {
    func routeToPolicyInformation(_ typeInfo: VerifyPolicyInfoType)
  
    
    //Refactor
    func routeToProfileViewController()
}

protocol AddPolicyDataPassing {
    var dataStore: AddPolicyDataStore? { get set}
}

class AddPolicyRouter: NSObject, AddPolicyRoutingLogic, AddPolicyDataPassing {
    weak var viewController: AddPolicyViewController?
    var dataStore: AddPolicyDataStore?
    
    
    func routeToProfileViewController() {
        let profileVC = viewController?.navigationController?.viewControllers.first(where: ({ $0 is ProfileViewController })) as? ProfileViewController
        var profileDS = profileVC?.router?.dataStore
        
        self.passDataToProfile(needsUpdate: true, destination: &profileDS)
        self.navigateToProfile()
    }
    
    // MARK: Routing
    func navigateToProfile() {
        self.viewController?.navigationController?.popViewController(animated: true)
    }
    
    
    func passDataToProfile(needsUpdate: Bool, destination: inout ProfileDataStore?){
        destination?.needsUpdateInsurancePolicies = needsUpdate
        destination?.needsUpdateAdvisorData = needsUpdate
    }
    
    func routeToPolicyInformation(_ typeInfo: VerifyPolicyInfoType) {
        
        switch typeInfo {
            
            case .certificate:
                let storyboard = UIStoryboard.registerCheck()
                let examplePolicy = storyboard.instantiateViewController(withIdentifier: "ExamplePolicytype") as! ExamplePolicyViewController
                examplePolicy.type = .collective
                viewController?.present(examplePolicy, animated: true)
            
            case .policy:
                let storyboard = UIStoryboard.registerCheck()
                let examplePolicy = storyboard.instantiateViewController(withIdentifier: "ExamplePolicytype") as! ExamplePolicyViewController
                examplePolicy.type = .individual
                viewController?.present(examplePolicy, animated: true)
            
        }
        
        
    }
    
}
