//
//  PolicyWalletRouter.swift
//  SegurosMtyiOS
//
//  Created by Isidro Adan Garcia Solorio  on 1/19/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PolicyWalletRoutingLogic {
}

protocol PolicyWalletDataPassing {
    var dataStore: PolicyDetailDataStore? { get set }
}

class PolicyWalletRouter: NSObject, PolicyWalletRoutingLogic, PolicyWalletDataPassing {
    weak var viewController: PolicyWalletViewController?
    var dataStore: PolicyDetailDataStore?
    
}
