//
//  PolicyWalletModels.swift
//  SegurosMtyiOS
//
//  Created by Isidro Adan Garcia Solorio  on 1/19/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum PolicyWallet {
    // MARK: Use cases
    
    enum LoadData {
        struct ViewModel {
            var expDate: String
            var userName: String
            var name: String
            var planName: String
            var number: String
            var certificateId: String?
            var cardId: PolicyCardType
            var isCertificateHidden: Bool
            var planForm: String
            var policyCode: String
        }
    }
}
