//
//  AddEmergencyContactInteractor.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 20/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import RxSwift

protocol AddEmergencyContactBusinessLogic {
    func validateName(request: AddEmergencyContact.ValidateName.Request)
    func validatePhoneNumber(request: AddEmergencyContact.ValidatePhoneNumber.Request)
    func validateEmail(request: AddEmergencyContact.ValidateEmail.Request)
    func savePictureOfEmergencyContact(request: AddEmergencyContact.SavePictureEmergencyContact.Request)
    func addEmergencyContact(request: AddEmergencyContact.AddEmergencyContact.Request) 
}

protocol AddEmergencyContactDataStore {
    //var myDataStoreVar: String { get set }
}

class AddEmergencyContactInteractor: AddEmergencyContactBusinessLogic, AddEmergencyContactDataStore {
    var presenter: (AddEmergencyContactPresentationLogic & ExpiredSessionPresentationLogic & ErrorPresentationLogic)?
    var worker: EmergencyContactsWorker?
    
    // MARK: DataStore
    var disposableBag: DisposeBag = DisposeBag()
    // MARK: Do something
    
    /**
     Es disparado cuando se necesita validar el nombre utilizada para editar un contacto de emergencia
     - parameter request: teléfono a validar.
     */
    func validateName(request: AddEmergencyContact.ValidateName.Request) {
        if worker == nil {
            worker = EmergencyContactsWorker()
        }
        
        if let result = worker?.validateName(request.name) {
            let response = AddEmergencyContact.ValidateName.Response(validationState: result)
            self.presenter?.presentNameValidation(validationState: response)
        }
    }
    
    /**
     Es disparado cuando se necesita validar el número de teléfono utilizada para editar un contacto de emergencia
     - parameter request: teléfono a validar.
     */
    func validatePhoneNumber(request: AddEmergencyContact.ValidatePhoneNumber.Request) {
        if worker == nil {
            worker = EmergencyContactsWorker()
        }
        
        if let result = worker?.validatePhoneNumber(request.phoneNumber) {
            let response = AddEmergencyContact.ValidatePhoneNumber.Response(validationState: result)
            self.presenter?.presentPhoneNumberValidation(validationState: response)
        }
    }
    
    func validateEmail(request: AddEmergencyContact.ValidateEmail.Request) {
        if worker == nil {
            worker = EmergencyContactsWorker()
        }
        
        if let result = worker?.validateEmail(request.email) {
            let response = AddEmergencyContact.ValidateEmail.Response(validationState: result)
            self.presenter?.presentEmailValidation(validationState: response)
        }
    }
    
    func savePictureOfEmergencyContact(request: AddEmergencyContact.SavePictureEmergencyContact.Request) {
        if worker == nil {
            worker = EmergencyContactsWorker()
        }
        
        worker?.savePictureOfEmergencyContact(picture: request.picture).subscribe({ [weak self] event in
            switch event {
            case .next(let result):
                let response = AddEmergencyContact.SavePictureEmergencyContact.Response(isSuccess: true, path: result)
                self?.presenter?.presentSavePictureEmergencyContact(response: response)
            case .error(_):
                let response = AddEmergencyContact.SavePictureEmergencyContact.Response(isSuccess: false, path: nil)
                self?.presenter?.presentSavePictureEmergencyContact(response: response)
                
            default:
                break
            }
        }).disposed(by: self.disposableBag)
    }
    
    func addEmergencyContact(request: AddEmergencyContact.AddEmergencyContact.Request) {
        if worker == nil {
            worker = EmergencyContactsWorker()
        }
        
        worker?.addEmergencyContact(emergencyContactID: request.emergencyContactID, picture: request.picture ?? "", name: request.name ?? "", phone: request.phone ?? "", email: request.email ?? "").subscribe({ [weak self] event in
            switch event {
            case .next(let result):
                let response = AddEmergencyContact.AddEmergencyContact.Response(isSuccess: result)
                self?.presenter?.presentAddEmergencyContact(response: response)
            case .error(let error):
                switch error {
                case NetworkingError.unauthorized:
                    self?.presenter?.presentExpiredSession()
                default:
                    self?.presenter?.presentError(error)
                }
            default:
                break
            }
        }).disposed(by: self.disposableBag)
    }
}
