//
//  AddEmergencyContactPresenter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 20/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol AddEmergencyContactPresentationLogic {
    func presentNameValidation(validationState: AddEmergencyContact.ValidateName.Response)
    func presentPhoneNumberValidation(validationState: AddEmergencyContact.ValidatePhoneNumber.Response)
    func presentEmailValidation(validationState: AddEmergencyContact.ValidateEmail.Response)
    func presentSavePictureEmergencyContact(response: AddEmergencyContact.SavePictureEmergencyContact.Response)
    func presentAddEmergencyContact(response: AddEmergencyContact.AddEmergencyContact.Response)
}

class AddEmergencyContactPresenter: AddEmergencyContactPresentationLogic {
    weak var viewController: (AddEmergencyContactDisplayLogic & ExpiredSessionDisplayLogic & ErrorDisplayLogic)?
    
    // MARK: Do something
    func presentNameValidation(validationState: AddEmergencyContact.ValidateName.Response) {
        let viewModel = AddEmergencyContact.ValidateName.ViewModel(validationState: validationState.validationState)
        self.viewController?.displayNameValidation(viewModel: viewModel)
    }
    
    func presentPhoneNumberValidation(validationState: AddEmergencyContact.ValidatePhoneNumber.Response) {
        let viewModel = AddEmergencyContact.ValidatePhoneNumber.ViewModel(validationState: validationState.validationState)
        self.viewController?.displayPhoneNumberValidation(viewModel: viewModel)
    }
    
    func presentEmailValidation(validationState: AddEmergencyContact.ValidateEmail.Response) {
        let viewModel = AddEmergencyContact.ValidateEmail.ViewModel(validationState: validationState.validationState)
        self.viewController?.displayEmailValidation(viewModel: viewModel)
    }
    
    /**
     Método que manda al viewController el ViewModel para notificar el resultado de la asignación de una imagen a un contacto
     Parameters:
     - response: ViewModel con un bool de success o failed
     */
    func presentSavePictureEmergencyContact(response: AddEmergencyContact.SavePictureEmergencyContact.Response) {
        let viewModel = AddEmergencyContact.SavePictureEmergencyContact.ViewModel(isSuccess: response.isSuccess, path: response.path ?? "")
        self.viewController?.displaySavePictureEmergencyContact(viewModel: viewModel)
    }
    
    func presentAddEmergencyContact(response: AddEmergencyContact.AddEmergencyContact.Response) {
        let viewModel = AddEmergencyContact.AddEmergencyContact.ViewModel(isSuccess: response.isSuccess)
        self.viewController?.displayAddEmergencyContact(viewModel: viewModel)
    }
}

/**
 Extensión para mostrar alerta con un tipo de error
 */
extension AddEmergencyContactPresenter: ErrorPresentationLogic {
    func presentError(_ error: Error) {
        var message: String!
        switch error {
        case NetworkingError.noInternet:
            message = LocalizableKeys.Profile.EditProfile.errorNoInternet
            viewController?.displayError(with: message)
        case NetworkingError.unauthorized:
            presentExpiredSession()
        case NetworkingError.noSuccessStatusCode(_, _):
            message = LocalizableKeys.General.serviceError
            viewController?.displayError(with: message)
        default:
            message = LocalizableKeys.General.serviceError
            viewController?.displayError(with: message)
        }
    }
}

/**
 Extensión para mostrar alerta de expiración de token
 */
extension AddEmergencyContactPresenter : ExpiredSessionPresentationLogic {
    func presentExpiredSession() {
        self.viewController?.displayExpiredSession()
    }
}
