//
//  AddEmergencyContactRouter.swift
//  SegurosMtyiOS
//
//  Created by Erwin Perez Tellez on 20/01/18.
//  Copyright (c) 2018 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddEmergencyContactRoutingLogic {
    func goToPerfilViewController()
}

protocol AddEmergencyContactDataPassing {
    var dataStore: AddEmergencyContactDataStore? { get }
}

class AddEmergencyContactRouter: NSObject, AddEmergencyContactRoutingLogic, AddEmergencyContactDataPassing {
    weak var viewController: AddEmergencyContactViewController?
    var dataStore: AddEmergencyContactDataStore?
    
    // MARK: Routing
    
    func goToPerfilViewController() {
        if let menuVC = self.viewController?.presentingViewController as? MenuViewController {
            if let navigationProfileVC = menuVC.viewControllers?.first as? UINavigationController {
                if let profileVC = navigationProfileVC.viewControllers.first as? ProfileViewController {
                    if let pruebaVC = profileVC.childViewControllers[0] as? ProfileInformationViewController {
                        pruebaVC.emergencyContacts = nil
                        pruebaVC.reloadEmergencyContacts()
                        self.viewController?.dismiss(animated: true, completion: nil)
                    }
                }
            }
        }
    }
}
