//
//  ProfileModels.swift
//  SegurosMtyiOS
//
//  Created by Isidro Adan Garcia Solorio  on 12/7/17.
//  Copyright (c) 2017 IA Interactive. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Profile {
    // MARK: Use cases
    
    enum UserInfo {
        struct ViewModel {
            var firstName: String
            var lastName: String
            var polizy: String?
            var birthDate: String
            var email: String
            var profilePic: UIImage
        }
    }
    
    enum EmergencyContacts {
        struct Response {
            var error: Swift.Error?
            var contacts: [String]?
        }
        struct ViewModel {
            var isInternetAvailable: Bool
            var contacts: [String]?
        }
    }
    
    enum InsurancePolicies {
        struct ViewModel {
            var insurancePolicies: [InsurancePolicy]
        }
    }
    
    enum AdvisorInfo {
        struct ViewModel {
            var name: String?
            var phone: String?
            var email: String?
        }
    }
}
